### ISSUE TITLE
대조군 추가 - Static

### ISSUE THREAD

**Issue by leafriend** [leafriend/eICIC#2]
1. 맨처음 알고리즘 수행 전 macro/pico에 대한 cell association을 결정  
   (TX_POWER/d<sup>4</sup>)<sub>macro</sub> &le; CRE'&times;(TX_POWER/d<sup>4</sup>)<sub>pico</sub> 일 경우 pico 그외 macro로 결정  
   (CRE bias는 dB 단위로 주어짐. 변환 필요. CRE bias = 10log<sub>10</sub>CRE')
2. macro가 타임 시퀀스 중 일정 비율의 타임에서 off됨  
     ABS ratio 에 따라 결정.  
     (e.g. t < ABS ratio: ABS mode 그외 non-ABS mode)  
     이 때 모든 macro는 동일한 상태로 동작 ABS 비율도 동일한 비율이 됨  
     (추후 기지국별로 다르게 동작하게 할 "수"도 있음. 되도록 하지 말자!!)
3. 이 때 1에서 macro로 연결된 이용자는 off, 나머지 이용자는 그대로 pico로 연결

**Comment by leafriend** [comment]
비교식 (TX_POWER/d<sup>4</sup>)<sub>macro</sub> &le; CRE'&times;(TX_POWER/d<sup>4</sup>)<sub>pico</sub>은 CRE'을 쓰고 있는데 CRE bias는 언제 쓰는지 확인 필요.

**Comment by leafriend** [comment]
6b041c0ce4332c7d6b458e9ce6ae069266609868 커밋으로 클로즈

**Comment by pooheup** [comment]
dB 단위의 CRE bias 값으로 입력을 받고
이를 CRE'으로 변경하여 적용.
실제 적용 자체는 dB 단위의 값으로 하므로,
입력은 dB로 받게 함.
(실험 결과는 dB 값에 대해서 표현할 것이므로)

**Comment by leafriend** [comment]
@pooheup 그럼 CRE bias = 10log<sub>10</sub>CRE' 이 식이 반대로 되어야 하는 거 아냐?

**Comment by pooheup** [comment]
현재 static에서 bias 값이 어떻게 주어졌는지요?

개인적으로는 시뮬레이션 시작할때 
ABS ratio 및 CRE bias 를 조절 (혹은 입력) 할 수 있게 했으면 함

**Comment by pooheup** [comment]
@leafriend 응?? 깨어있네?

**Comment by pooheup** [comment]
@leafriend 아니 저건 그냥 둘의 관계식을 써 놓은거였음요. 저거 역으로 연산해서 bias 값 주어지면 CRE'값을 구하는게 맞지요

**Comment by pooheup** [comment]
@leafriend 근데 왜 여기서 이렇게 대화하는거지? ㅋㅋㅋㅋ

**Comment by leafriend** [comment]
@pooheup ㅋㅋㅋ ㅇㅋㄷㅋ 어쩐지 이상하더라. 역으로 계산하게 수정해 놓을게. 참고로 v1.2.0은 CRE'이 현재 1이고. 기본값도 알려주면 패치해서 v1.2.1 보내줄게.

**Comment by leafriend** [comment]
C': CRE
C: CRE bias

10 &times; log<sub>10</sub>C' = C
log<sub>10</sub>C' = C/10
log<sub>10</sub>C' = C/10 &times; log<sub>10</sub>10
log<sub>10</sub>C' = log<sub>10</sub>10<sup>C/10</sup>
C' = 10<sup>C/10</sup>
